# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
        args:
          - --assume-in-merge
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        # entry: gitleaks git --verbose # let's scan all repo, not staged diff
        # language: golang
        # pass_filenames: false
  # - repo: https://github.com/crytic/slither/
  #   rev: 0.11.3
  #   hooks:
  #     - id: slither
  #       # name: Slither
  #       # description: Run Slither on your project
  #       # entry: slither
  #       # args:
  #       #   - .
  #       # pass_filenames: false
  #       # language: python
  #       # files: \.sol$
  # # - repo: https://github.com/Consensys/mythril
  # #   rev: v0.24.8
  # #   hooks:
  # #     - id: mythril
