[profile.default]
solc = "0.8.29"
evm_version = "prague"
bytecode_hash = "none"
cbor_metadata = false
src = "src"
out = "out"
libs = ["lib"]
always_use_create_2_factory = true
via-ir = true
optimizer = true
optimizer_runs = 170

fs_permissions = [
  { access = "read", path = "src" },
  { access = "read", path = "src/" },
  { access = "read", path = "./src" },
  { access = "read", path = "./src/" }
]

[lint]
lint_on_build = false

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
